UserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: ${self:service}-${self:provider.stage}-user-pool
    UsernameAttributes:
      - email
    UsernameConfiguration:
      CaseSensitive: true
    MfaConfiguration: OFF
    AccountRecoverySetting:
      RecoveryMechanisms:
        - Name: verified_email
          Priority: 1
    AdminCreateUserConfig:
      AllowAdminCreateUserOnly: false
    DeletionProtection: ACTIVE
    Policies:
      PasswordPolicy:
        MinimumLength: 8
        RequireUppercase: true
        RequireLowercase: true
        RequireNumbers: true
        RequireSymbols: true

UserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    ClientName: ${self:service}-${self:provider.stage}-UserPoolClient
    UserPoolId: !Ref UserPool
    ExplicitAuthFlows:
      - ALLOW_USER_PASSWORD_AUTH
    TokenValidityUnits:
      AccessToken: hours
    AccessTokenValidity: 12
    RefreshTokenRotation:
      Feature: ENABLED
      RetryGracePeriodSeconds: 0
